spring.application.name=lojinha
spring.datasource.url=jdbc:mysql://localhost:3306/minhaloja
spring.datasource.username=root
spring.datasource.password=Pindamon18#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true